### ISSUE TITLE
No Docker to run rra-vt

### ISSUE THREAD

**Issue by olafveerman** [WorldBank-Transport/ram-backend#192]
`rra-vt` doesn't run on the staging environment, as it can't connect to Docker:

```
Command failed: docker run -u $(id -u) --rm -v /tmp:/data --name p2002s2002-bounds wbtransport/rra-vt tippecanoe -l bounds -e /data/p2002s2002-tiles /data/p2002s2002-fc.geojson docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?. See 'docker run --help'.
```

cc @danielfdsilva

**Comment by danielfdsilva** [comment]
@olafveerman It seems that is one of those docker running inside docker
problems. Can docker be made to run inside a ECS container?

Wasn't that done to the standalone version of the app?

**Comment by olafveerman** [comment]
The API running on ECS didn't have a volume associated with it. https://github.com/WorldBank-Transport/ram-backend/commit/63e6c97def01f64492363f1ceb726c72719e7918 fixes the connection issues to the Docker daemon, but now the Project Setup fails with the following error message:

```
/data/p2002s2002-fc.geojson: No such file or directory
0 features, 10 bytes of geometry, 2 bytes of separate metadata, 0 bytes of string pool
Did not read any valid geometries
```

**Comment by danielfdsilva** [comment]
This happens because volumes don’t work with docker-in-docker.
The inner most docker is using the socket from the host, which means that any mounted volumes are searched for in the host not in the docker.

Fixed in https://github.com/WorldBank-Transport/ram-backend/commit/27cca6ace241f7f497f43f7fab9bcfdbbcede55a by mounting the host folder on the first docker
